info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
grails:
  controllers:
    defaultScope: singleton
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
  spring:
    security:
      active: false
  mime:
    disable:
      accept:
        header:
          userAgents:
          - Gecko
          - WebKit
          - Presto
          - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
      - text/html
      - application/xhtml+xml
      js: text/javascript
      json:
      - application/json
      - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
      - application/hal+json
      - application/hal+xml
      xml:
      - text/xml
      - application/xml

dataSource:
  pooled: true
  jmxExport: true
  driverClassName: com.mysql.cj.jdbc.Driver
  dialect: org.hibernate.dialect.MySQL8Dialect
  username: root
  password: Pop2120Eye
  password_macbookair: Greenline2021
  password_macmini: Pop2120Eye
  url: jdbc:mysql://localhost:3306/doctor_booking_v1?useSSL=false&serverTimezone=UTC
  dbCreate: update 

environments:
  development:
    dataSource:
      dbCreate: update
  test:
    dataSource:
      dbCreate: update
  production:
    dataSource:
      dbCreate: update
